// One-off generator: reads a world GeoJSON and bakes it into compact static SVG
// path strings (equirectangular projection) for the reach map. No runtime map
// library — the output is plain strings committed to lib/worldMap.ts.
import { readFileSync, writeFileSync } from "node:fs";

const geo = JSON.parse(
  readFileSync(new URL("./world.geojson", import.meta.url), "utf8")
);

const W = 1000;
const H = 500;
// Equirectangular: lon [-180,180] -> [0,W], lat [90,-90] -> [0,H].
const px = (lon) => Math.round(((lon + 180) / 360) * W);
const py = (lat) => Math.round(((90 - lat) / 180) * H);

// Highlight targets by GeoJSON name -> our ISO code.
// This dataset is low-res: the UK is a single "England" polygon (Great Britain
// island) and the US is "USA". Ireland is a separate country — not mapped to gb.
const targets = {
  Ghana: "gh",
  England: "gb",
  India: "in",
  Turkey: "tr",
  Canada: "ca",
  USA: "us",
};

// Build an SVG path from a polygon/multipolygon coordinate set.
// `step` decimates points (keep every Nth) to shrink the base layer.
function coordsToPath(geometry, step) {
  const polys =
    geometry.type === "Polygon" ? [geometry.coordinates] : geometry.coordinates;
  let d = "";
  for (const poly of polys) {
    for (const ring of poly) {
      if (ring.length < 4) continue;
      let seg = "";
      let last = "";
      for (let i = 0; i < ring.length; i++) {
        // Always keep first + last; decimate the middle.
        if (i !== 0 && i !== ring.length - 1 && i % step !== 0) continue;
        const [lon, lat] = ring[i];
        const p = `${px(lon)} ${py(lat)}`;
        if (p === last) continue;
        seg += (seg === "" ? "M" : "L") + p;
        last = p;
      }
      if (seg) d += seg + "Z";
    }
  }
  return d;
}

let base = "";
const highlight = {};

for (const f of geo.features) {
  const name = f.properties?.name;
  if (name === "Antarctica") continue; // not needed, huge point count
  const code = targets[name];
  if (code) {
    highlight[code] = (highlight[code] ?? "") + coordsToPath(f.geometry, 1);
  } else {
    base += coordsToPath(f.geometry, 3); // decimated outline layer
  }
}

const out = `// AUTO-GENERATED by scripts/genWorldMap.mjs — do not edit by hand.
// Equirectangular projection, viewBox 0 0 ${W} ${H}. Base = faint world outline
// (all countries except Antarctica, decimated). Highlights = the six client
// countries at full detail, filled on the reach map.
export const WORLD_VIEWBOX = "0 0 ${W} ${H}";
export const worldOutlinePath = ${JSON.stringify(base)};
export const highlightPaths: Record<string, string> = ${JSON.stringify(highlight)};
`;

writeFileSync("lib/worldMap.ts", out);

const kb = (s) => (Buffer.byteLength(s, "utf8") / 1024).toFixed(1);
console.log("base outline:", kb(base), "KB");
for (const k of Object.keys(highlight))
  console.log("  highlight", k, kb(highlight[k]), "KB");
console.log("total file:", kb(out), "KB");
